DesignMenu:
    ContextMenuTextItem:
        text: "interpolation (" + self.parent.interpolation + ")"
        ContextMenu:
            ContextMenuTextItem:
                text: "cubic"
                on_release: self.parent.parent.parent.interpolation = self.text;
            ContextMenuTextItem:
                text: "linear"
                on_release: self.parent.parent.parent.interpolation = self.text