PageLayout:
    countOfPages: 3
    GridLayout:
        cols: 4
        rows: 4
        Button:
            text: 'button 1'
            # on_press: self.parent.change_page(self.number+1 )
        Button:
            text: 'button 1.2'
        Button:
            text: 'button 1.3'
        Button:
            text: 'button 1.3'
    Button:
        text: 'button 2'
        # on_press: change_page(self.number+1)
    Button:
        text: 'button 3'
        # on_press: change_page(self.number+1)
